name: ElasticSpells CICD Learning
run-name: ${{ github.actor }} is running ElastiSpells workflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: [ $default-branch ]

jobs:
  my-job-that-checks-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: node -v

  test-backend:
    runs-on: ubuntu-latest
    needs: my-job-that-checks-node-version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm' # TODO find out what this does exactly
      - run: node -v
      - name: 'Run npm install (npm clean-install)'
        run: npm ci                                                 # `npm ci` or `npm clean-install` is a comand similar to `npm install` designed for CI/CD
      - run: npm run build --if-present
      - name: Run backend tests
        run: npm run test
      - name: Try Deploying                                         # do this in a separate job? why yes, why not.
        run: echo 'TODO deploying this thing!'